name: Gradle

on:
  push:
    branches: [master, ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]

jobs:
    Test:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v1

            -   name: Set up JDK 11
                uses: actions/setup-java@v1
                with:
                    java-version: 11

            -   name: Make gradlew executable
                run: chmod +x ./gradlew

            -   name: Build with Gradle
                run: ./gradlew build

            -   name: Test with Gradle
                run: ./gradlew test
                env:
                    CI: true
